#!/bin/bash
cd /lcrc/globalscratch/dan/logs/$1
#all_files=$(ls)
rm $2/$1.thanos_events.txt
#echo "$all_files"

for num in {1..200}
do
if ! ls | grep -x $num.log;
then
	echo "$(tput setaf 1) $num is not there $(tput init)"
	echo $num>> $2/$1.thanos_events.txt
fi
done
